# Generated by Django 4.1.4 on 2022-12-10 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255, unique=True)),
                ('device_condition', models.CharField(choices=[('new', 'new'), ('used', 'used')], max_length=255)),
                ('is_booked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneAllocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provide_time', models.DateField(auto_now_add=True)),
                ('received_time', models.DateField(blank=True, null=True)),
                ('received_condition', models.CharField(choices=[('good', 'good'), ('bad', 'bad')], max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.companyinfo')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Phone.phone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
